### ISSUE TITLE
TODO: smudge size reporting

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#162]
We need to be able to compare smudge sizes for many empirical datasets. This can be either with automated coverage/smudge inference (with the current fishnet algorithm), or with user specified coverage (in that case the algorithm simply project the fishnet and give sizes of cutouts).

The values should be reported in a single tab-delimited line.

Besides sizes of all possible smudges (64 peaks), the first column should be sample/species name (user argument `-t`), number of error k-mer pairs and total number of k-mers;

- [x] make sure the user defined coverage works
- [x] generate the reporting string given kmer pair smudge assignment (i.e. fishnet projection atm, but in theory could be anything)
   - [x] have the capacity to generate the header too (does not have to be production code, but we should be sure which value is which); the smudge size columns should be "s<As>,<Bs>", where <As> and <Bs> are ploidies of A and Bs of that smudge. So, s2,1 will be for AAB, s2,2 will be AABB etc...
- [x] report it (stdout) or in a separated file (but should be easily catinable)
- [x] (Kamil) generate a list of genomes to test this with of known ploidies.
